In [ ]:
import yfinance as yf
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, precision_score

import datetime as dt
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import time

In [ ]:
#This analyses the accuracy analyst recommendations, data compares -2m and -3m recommendations, backtest month should be last month to the start of this month, this meanning current month

def rec_analysis(stock, k=0.5, compare = False):
  recs = yf.Ticker(stock).recommendations
  recs = recs.iloc[2:, 1:]

  old_bullarity = (recs.iloc[1,0] + recs.iloc[1,1])/recs.iloc[1].sum()
  new_bullarity = (recs.iloc[0,0] + recs.iloc[0,1])/recs.iloc[0].sum()

  if compare:
    if new_bullarity > old_bullarity:
      return 1
    else:
      return 0

  if new_bullarity > k:
    return 1
  else:
    return 0


In [ ]:
def change_days(date_str, days):
    import datetime as dt
    date = dt.datetime.strptime(date_str, "%Y-%m-%d")

    new_date = date + timedelta(days=days)

    return new_date.strftime("%Y-%m-%d")

def change_months(date_str, monthss):
  import datetime as dt
  date_obj = datetime.strptime(date_str, "%Y-%m-%d")

  new_date = date_obj + relativedelta(months=monthss)

  return new_date.strftime("%Y-%m-%d")

def backtest(stock, date):#function will return how much the stock price changed in the coming month
  enddate = change_months(date, 1)

  initial_price = yf.Ticker(stock).history(start = change_days(date, -5), end = date).tail(1) #the closing price before date
  new_price = yf.Ticker(stock).history(start = date, end = enddate).tail(1)#Closing price of final day

  #print(order)
  pct_change = (float(new_price["Close"].iloc[0])-float(initial_price["Close"].iloc[0]))/float(initial_price["Close"].iloc[0])

  print('\n',f"[------=====◼️◼️◼️◼️◼️ Backtesting {stock} [{date} --> {enddate}], {pct_change} ◼️◼️◼️◼️◼️=====--------]")
  return pct_change

In [ ]:
backtest('wday', '2026-02-01')


 [------=====◼️◼️◼️◼️◼️ Backtesting wday [2026-02-01 --> 2026-03-01], -0.23839895924340457 ◼️◼️◼️◼️◼️=====--------]


-0.23839895924340457

In [ ]:
stocks = ['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'AON', 'APA', 'APO', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BALL', 'BAC', 'BAX', 'BDX', 'BRK-B', 'BBY', 'TECH', 'BIIB', 'BLK', 'BX', 'XYZ', 'BK', 'BA', 'BKNG', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF-B', 'BLDR', 'BG', 'BXP', 'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CAT', 'CBOE', 'CBRE', 'CDW', 'COR', 'CNC', 'CNP', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'COIN', 'CL', 'CMCSA', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CPAY', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CRWD', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DRI', 'DDOG', 'DVA', 'DECK', 'DE', 'DELL', 'DAL', 'DVN', 'DXCM', 'FANG', 'DLR', 'DG', 'DLTR', 'D', 'DPZ', 'DASH', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK', 'DD', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'ELV', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'EG', 'EVRG', 'ES', 'EXC', 'EXE', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'F', 'FTNT', 'FTV', 'FOXA', 'BEN', 'FCX', 'IT', 'GE', 'GEHC', 'GEN', 'GNRC', 'GD', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GL', 'GDDY', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'DOC', 'HSIC', 'HSY', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 'IFF', 'IP', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KKR', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LII', 'LLY', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LULU', 'LYB', 'MTB', 'MPC', 'MKTX', 'MAR', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PLTR', 'PANW', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SW', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SMCI', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TER', 'TSLA', 'TXN', 'TPL', 'TXT', 'TMO', 'TJX', 'TKO', 'TTD', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VTRS', 'VICI', 'V', 'VST', 'VMC', 'WRB', 'GWW', 'WAB', 'WMT', 'DIS', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WY', 'WSM', 'WMB', 'WTW', 'WDAY', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZTS']

len(stocks)

485

In [ ]:
k = 0.9
compare = False
date = '2026-02-01'

y_pred = []
y_true = []

for stock in stocks:
  time.sleep((0.1))
  try:
    y_pred.append(rec_analysis(stock, compare = compare, k = k))
  except Exception as e:
    print(stock, e)
    y_pred.append(999)

for stock in stocks:
  time.sleep((0.5))
  if backtest(stock, date) > 0:
    y_true.append(1)
  else:
    y_true.append(0)

L index 0 is out of bounds for axis 0 with size 0

 [------=====◼️◼️◼️◼️◼️ Backtesting MMM [2026-02-01 --> 2026-05-01], -0.05007897800144426 ◼️◼️◼️◼️◼️=====--------]

 [------=====◼️◼️◼️◼️◼️ Backtesting AOS [2026-02-01 --> 2026-05-01], -0.1143012895639244 ◼️◼️◼️◼️◼️=====--------]

 [------=====◼️◼️◼️◼️◼️ Backtesting ABT [2026-02-01 --> 2026-05-01], -0.14858016726027864 ◼️◼️◼️◼️◼️=====--------]

 [------=====◼️◼️◼️◼️◼️ Backtesting ABBV [2026-02-01 --> 2026-05-01], -0.09144382957048916 ◼️◼️◼️◼️◼️=====--------]

 [------=====◼️◼️◼️◼️◼️ Backtesting ACN [2026-02-01 --> 2026-05-01], -0.3180402859527281 ◼️◼️◼️◼️◼️=====--------]

 [------=====◼️◼️◼️◼️◼️ Backtesting ADBE [2026-02-01 --> 2026-05-01], -0.1850639531882726 ◼️◼️◼️◼️◼️=====--------]

 [------=====◼️◼️◼️◼️◼️ Backtesting AMD [2026-02-01 --> 2026-05-01], 0.28978157429479584 ◼️◼️◼️◼️◼️=====--------]

 [------=====◼️◼️◼️◼️◼️ Backtesting AES [2026-02-01 --> 2026-05-01], -0.010238882077549282 ◼️◼️◼️◼️◼️=====--------]

 [------=====◼️◼️◼️◼️◼

In [ ]:
cm = confusion_matrix(y_true, y_pred)
cr = classification_report(y_true, y_pred)

print(cm, '\n', cr)

[[225  12   0]
 [236  11   1]
 [  0   0   0]] 
               precision    recall  f1-score   support

           0       0.49      0.95      0.64       237
           1       0.48      0.04      0.08       248
         999       0.00      0.00      0.00         0

    accuracy                           0.49       485
   macro avg       0.32      0.33      0.24       485
weighted avg       0.48      0.49      0.36       485



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
407/(407+78)

0.8391752577319588